backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "specialists"
    label: "Especialistas"
    folder: "src/pages/specialists"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "specialist"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Especialidad', name: 'specialty', widget: 'select', options: ['Published', 'Featured', 'Draft'], default: 'Published'}  
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Foto", name: "featuredimage", widget: image}
      - {label: "Detalle", name: "body", widget: "markdown"}
      - {label: 'Servicios', name: 'services', widget: 'relation', collection: 'services', searchFields: ['title'], valueField: 'title', multiple: true}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
  - name: "services"
    label: "Servicios"
    folder: "src/pages/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Especialidad', name: 'specialty', widget: 'select', options: ['Published', 'Featured', 'Draft'], default: 'Published'}  
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Detalle", name: "body", widget: "markdown"}
      - {label: 'Especialistas', name: 'specialists', widget: 'relation', collection: 'specialists', searchFields: ['title'], valueField: 'title', multiple: true}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}

  